cache:
  directories:
    - $HOME/google-cloud-sdk
sudo: required
services:
  - docker
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SHA=$(git rev-parse HEAD)
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project k8s-multi-services
  - gcloud config set compute/zone southamerica-east1-c
  - gcloud container clusters get-credentials multi-services
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build -f ./client/development.Dockerfile -t douglira/test-webapp ./client
  - echo "COMMIT SHA $SHA"
  - echo "TAVIS COMMIT $TRAVIS_COMMIT"

script:
  - docker run -e CI=true douglira/test-webapp npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main